name: Alerta DevOps

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -d "Nuevo commit en la rama main del repositorio DevopsPages" \
          ntfy.sh/devops-itla
